/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.EventQueue;

/**
 *
 * @author ORTEGA
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificationsPane = new javax.swing.JLayeredPane();
        background5 = new javax.swing.JLabel();
        backText4 = new javax.swing.JLabel();
        Back4 = new javax.swing.JButton();
        transactionTitle1 = new javax.swing.JLabel();
        cheekyLine1 = new javax.swing.JPanel();
        transactionHistoryPanel1 = new javax.swing.JPanel();
        Parent = new javax.swing.JPanel();
        mainMenuLayeredPane = new javax.swing.JLayeredPane();
        background = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        profileArea = new javax.swing.JPanel();
        profilePicture = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        notificationButton = new javax.swing.JButton();
        buttonsArea = new javax.swing.JPanel();
        depositButton = new javax.swing.JButton();
        bankTransferButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        transactionHistoryButton = new javax.swing.JButton();
        currentBalanceText = new javax.swing.JLabel();
        balanceTitle = new javax.swing.JLabel();
        depositPane = new javax.swing.JLayeredPane();
        background1 = new javax.swing.JLabel();
        profileArea1 = new javax.swing.JPanel();
        paneTitle = new javax.swing.JLabel();
        currentBalanceText1 = new javax.swing.JLabel();
        balanceTitle1 = new javax.swing.JLabel();
        formattedInputField = new javax.swing.JFormattedTextField();
        formattedInputFieldBackground = new javax.swing.JLabel();
        enterAmount = new javax.swing.JLabel();
        depositButtonsArea = new javax.swing.JPanel();
        Deposit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        backText = new javax.swing.JLabel();
        depositText = new javax.swing.JLabel();
        withdrawPane = new javax.swing.JLayeredPane();
        background2 = new javax.swing.JLabel();
        profileArea2 = new javax.swing.JPanel();
        paneTitle1 = new javax.swing.JLabel();
        currentBalanceText2 = new javax.swing.JLabel();
        balanceTitle2 = new javax.swing.JLabel();
        formattedInputField1 = new javax.swing.JFormattedTextField();
        formattedInputFieldBackground1 = new javax.swing.JLabel();
        enterAmount1 = new javax.swing.JLabel();
        withdrawButtonsArea = new javax.swing.JPanel();
        Back1 = new javax.swing.JButton();
        Withdraw = new javax.swing.JButton();
        backText1 = new javax.swing.JLabel();
        depositText1 = new javax.swing.JLabel();
        transactionHistoryPane = new javax.swing.JLayeredPane();
        background3 = new javax.swing.JLabel();
        backText2 = new javax.swing.JLabel();
        Back2 = new javax.swing.JButton();
        transactionTitle = new javax.swing.JLabel();
        cheekyLine = new javax.swing.JPanel();
        transactionHistoryPanel = new javax.swing.JPanel();
        bankTransferPane = new javax.swing.JLayeredPane();
        background4 = new javax.swing.JLabel();
        profileArea3 = new javax.swing.JPanel();
        paneTitle2 = new javax.swing.JLabel();
        currentBalanceText3 = new javax.swing.JLabel();
        balanceTitle3 = new javax.swing.JLabel();
        formattedInputField2 = new javax.swing.JFormattedTextField();
        formattedInputFieldBackground2 = new javax.swing.JLabel();
        enterAmount2 = new javax.swing.JLabel();
        depositButtonsArea1 = new javax.swing.JPanel();
        Deposit1 = new javax.swing.JButton();
        Back3 = new javax.swing.JButton();
        backText3 = new javax.swing.JLabel();
        depositText2 = new javax.swing.JLabel();
        formattedInputFieldBackground3 = new javax.swing.JLabel();
        formattedInputField3 = new javax.swing.JFormattedTextField();
        enterAmount3 = new javax.swing.JLabel();
        formattedInputFieldBackground4 = new javax.swing.JLabel();
        formattedInputField4 = new javax.swing.JFormattedTextField();
        enterAmount4 = new javax.swing.JLabel();

        notificationsPane.setPreferredSize(new java.awt.Dimension(402, 437));

        background5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FrameBackground/Frame 1.png"))); // NOI18N
        notificationsPane.add(background5);
        background5.setBounds(0, 0, 402, 437);

        backText4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backText4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backText4.setText("Back");
        notificationsPane.setLayer(backText4, javax.swing.JLayeredPane.MODAL_LAYER);
        notificationsPane.add(backText4);
        backText4.setBounds(10, 10, 110, 40);

        Back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Back4.setBorder(null);
        Back4.setContentAreaFilled(false);
        Back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenu(evt);
            }
        });
        notificationsPane.setLayer(Back4, javax.swing.JLayeredPane.PALETTE_LAYER);
        notificationsPane.add(Back4);
        Back4.setBounds(10, 10, 111, 36);

        transactionTitle1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        transactionTitle1.setForeground(new java.awt.Color(255, 255, 255));
        transactionTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionTitle1.setText("NOTIFICATIONS");
        notificationsPane.setLayer(transactionTitle1, javax.swing.JLayeredPane.PALETTE_LAYER);
        notificationsPane.add(transactionTitle1);
        transactionTitle1.setBounds(140, 0, 260, 50);

        javax.swing.GroupLayout cheekyLine1Layout = new javax.swing.GroupLayout(cheekyLine1);
        cheekyLine1.setLayout(cheekyLine1Layout);
        cheekyLine1Layout.setHorizontalGroup(
            cheekyLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        cheekyLine1Layout.setVerticalGroup(
            cheekyLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        notificationsPane.setLayer(cheekyLine1, javax.swing.JLayeredPane.PALETTE_LAYER);
        notificationsPane.add(cheekyLine1);
        cheekyLine1.setBounds(0, 60, 402, 2);

        transactionHistoryPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        transactionHistoryPanel1.setOpaque(false);

        javax.swing.GroupLayout transactionHistoryPanel1Layout = new javax.swing.GroupLayout(transactionHistoryPanel1);
        transactionHistoryPanel1.setLayout(transactionHistoryPanel1Layout);
        transactionHistoryPanel1Layout.setHorizontalGroup(
            transactionHistoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        transactionHistoryPanel1Layout.setVerticalGroup(
            transactionHistoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        notificationsPane.setLayer(transactionHistoryPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        notificationsPane.add(transactionHistoryPanel1);
        transactionHistoryPanel1.setBounds(10, 70, 382, 360);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking System");
        setName("mainMenuFrame"); // NOI18N
        setResizable(false);

        Parent.setBackground(new java.awt.Color(153, 255, 255));
        Parent.setOpaque(false);
        Parent.setLayout(new java.awt.CardLayout());

        mainMenuLayeredPane.setPreferredSize(new java.awt.Dimension(402, 437));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FrameBackground/Frame 1.png"))); // NOI18N
        mainMenuLayeredPane.add(background);
        background.setBounds(0, 0, 402, 437);

        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/logout icon.png"))); // NOI18N
        logOutButton.setBorder(null);
        logOutButton.setContentAreaFilled(false);
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        mainMenuLayeredPane.setLayer(logOutButton, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainMenuLayeredPane.add(logOutButton);
        logOutButton.setBounds(350, 20, 30, 30);

        profileArea.setOpaque(false);
        profileArea.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/default pf.png"))); // NOI18N
        profilePicture.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profileArea.add(profilePicture);

        userName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("USER");
        profileArea.add(userName);

        mainMenuLayeredPane.setLayer(profileArea, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainMenuLayeredPane.add(profileArea);
        profileArea.setBounds(0, 50, 402, 100);

        notificationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/bell.png"))); // NOI18N
        notificationButton.setBorder(null);
        notificationButton.setContentAreaFilled(false);
        notificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsActionPerformed(evt);
            }
        });
        mainMenuLayeredPane.setLayer(notificationButton, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainMenuLayeredPane.add(notificationButton);
        notificationButton.setBounds(20, 20, 30, 30);

        buttonsArea.setOpaque(false);
        buttonsArea.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        depositButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonIcons/depositButtonIcon.png"))); // NOI18N
        depositButton.setBorder(null);
        depositButton.setContentAreaFilled(false);
        depositButton.setPreferredSize(new java.awt.Dimension(58, 56));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        buttonsArea.add(depositButton);

        bankTransferButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonIcons/bankTransferIcon.png"))); // NOI18N
        bankTransferButton.setBorder(null);
        bankTransferButton.setContentAreaFilled(false);
        bankTransferButton.setPreferredSize(new java.awt.Dimension(58, 56));
        bankTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTransferButtonActionPerformed(evt);
            }
        });
        buttonsArea.add(bankTransferButton);

        withdrawButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonIcons/withdrawIcon.png"))); // NOI18N
        withdrawButton.setBorder(null);
        withdrawButton.setContentAreaFilled(false);
        withdrawButton.setPreferredSize(new java.awt.Dimension(58, 56));
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        buttonsArea.add(withdrawButton);

        transactionHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ButtonIcons/transactionHistoryIcon.png"))); // NOI18N
        transactionHistoryButton.setBorder(null);
        transactionHistoryButton.setContentAreaFilled(false);
        transactionHistoryButton.setPreferredSize(new java.awt.Dimension(58, 56));
        transactionHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryButtonActionPerformed(evt);
            }
        });
        buttonsArea.add(transactionHistoryButton);

        mainMenuLayeredPane.setLayer(buttonsArea, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainMenuLayeredPane.add(buttonsArea);
        buttonsArea.setBounds(0, 320, 402, 100);

        currentBalanceText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        currentBalanceText.setForeground(new java.awt.Color(255, 255, 255));
        currentBalanceText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBalanceText.setText("₱ 100000.00");
        mainMenuLayeredPane.setLayer(currentBalanceText, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainMenuLayeredPane.add(currentBalanceText);
        currentBalanceText.setBounds(0, 180, 400, 60);

        balanceTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        balanceTitle.setForeground(new java.awt.Color(255, 255, 255));
        balanceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceTitle.setText("Balance");
        mainMenuLayeredPane.setLayer(balanceTitle, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainMenuLayeredPane.add(balanceTitle);
        balanceTitle.setBounds(0, 160, 400, 30);

        Parent.add(mainMenuLayeredPane, "card2");

        depositPane.setPreferredSize(new java.awt.Dimension(402, 437));

        background1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FrameBackground/Frame 1.png"))); // NOI18N
        depositPane.add(background1);
        background1.setBounds(0, 0, 402, 437);

        profileArea1.setOpaque(false);
        profileArea1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        paneTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paneTitle.setForeground(new java.awt.Color(255, 255, 255));
        paneTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paneTitle.setText("Make a Deposit?");
        profileArea1.add(paneTitle);

        depositPane.setLayer(profileArea1, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(profileArea1);
        profileArea1.setBounds(0, 30, 402, 100);

        currentBalanceText1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        currentBalanceText1.setForeground(new java.awt.Color(255, 255, 255));
        currentBalanceText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBalanceText1.setText("₱ 100000");
        depositPane.setLayer(currentBalanceText1, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(currentBalanceText1);
        currentBalanceText1.setBounds(0, 140, 400, 60);

        balanceTitle1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        balanceTitle1.setForeground(new java.awt.Color(255, 255, 255));
        balanceTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceTitle1.setText("Balance");
        depositPane.setLayer(balanceTitle1, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(balanceTitle1);
        balanceTitle1.setBounds(0, 120, 400, 30);

        formattedInputField.setBorder(null);
        formattedInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedInputFieldActionPerformed(evt);
            }
        });
        depositPane.setLayer(formattedInputField, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(formattedInputField);
        formattedInputField.setBounds(90, 237, 220, 16);

        formattedInputFieldBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattedInputFieldBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/inputFieldBackground.png"))); // NOI18N
        depositPane.setLayer(formattedInputFieldBackground, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(formattedInputFieldBackground);
        formattedInputFieldBackground.setBounds(0, 230, 402, 30);

        enterAmount.setForeground(new java.awt.Color(255, 255, 255));
        enterAmount.setText("Enter amount");
        enterAmount.setToolTipText("");
        enterAmount.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        depositPane.setLayer(enterAmount, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(enterAmount);
        enterAmount.setBounds(80, 216, 240, 20);

        depositButtonsArea.setOpaque(false);
        depositButtonsArea.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        Deposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Deposit.setBorder(null);
        Deposit.setContentAreaFilled(false);
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenu(evt);
            }
        });
        depositButtonsArea.add(Deposit);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Back.setBorder(null);
        Back.setContentAreaFilled(false);
        depositButtonsArea.add(Back);

        depositPane.setLayer(depositButtonsArea, javax.swing.JLayeredPane.PALETTE_LAYER);
        depositPane.add(depositButtonsArea);
        depositButtonsArea.setBounds(0, 290, 402, 100);

        backText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backText.setText("Back");
        depositPane.setLayer(backText, javax.swing.JLayeredPane.MODAL_LAYER);
        depositPane.add(backText);
        backText.setBounds(80, 250, 100, 130);

        depositText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositText.setText("Deposit");
        depositPane.setLayer(depositText, javax.swing.JLayeredPane.MODAL_LAYER);
        depositPane.add(depositText);
        depositText.setBounds(217, 250, 100, 130);

        Parent.add(depositPane, "card2");

        withdrawPane.setPreferredSize(new java.awt.Dimension(402, 437));

        background2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FrameBackground/Frame 1.png"))); // NOI18N
        withdrawPane.add(background2);
        background2.setBounds(0, 0, 402, 437);

        profileArea2.setOpaque(false);
        profileArea2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        paneTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paneTitle1.setForeground(new java.awt.Color(255, 255, 255));
        paneTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paneTitle1.setText("Make a Withdrawal?");
        profileArea2.add(paneTitle1);

        withdrawPane.setLayer(profileArea2, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(profileArea2);
        profileArea2.setBounds(0, 30, 402, 100);

        currentBalanceText2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        currentBalanceText2.setForeground(new java.awt.Color(255, 255, 255));
        currentBalanceText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBalanceText2.setText("₱ 100000");
        withdrawPane.setLayer(currentBalanceText2, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(currentBalanceText2);
        currentBalanceText2.setBounds(0, 140, 400, 60);

        balanceTitle2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        balanceTitle2.setForeground(new java.awt.Color(255, 255, 255));
        balanceTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceTitle2.setText("Balance");
        withdrawPane.setLayer(balanceTitle2, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(balanceTitle2);
        balanceTitle2.setBounds(0, 120, 400, 30);

        formattedInputField1.setBorder(null);
        formattedInputField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedInputField1ActionPerformed(evt);
            }
        });
        withdrawPane.setLayer(formattedInputField1, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(formattedInputField1);
        formattedInputField1.setBounds(90, 237, 220, 16);

        formattedInputFieldBackground1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattedInputFieldBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/inputFieldBackground.png"))); // NOI18N
        withdrawPane.setLayer(formattedInputFieldBackground1, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(formattedInputFieldBackground1);
        formattedInputFieldBackground1.setBounds(0, 230, 402, 30);

        enterAmount1.setForeground(new java.awt.Color(255, 255, 255));
        enterAmount1.setText("Enter amount");
        enterAmount1.setToolTipText("");
        enterAmount1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        withdrawPane.setLayer(enterAmount1, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(enterAmount1);
        enterAmount1.setBounds(80, 216, 240, 20);

        withdrawButtonsArea.setOpaque(false);
        withdrawButtonsArea.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Back1.setBorder(null);
        Back1.setContentAreaFilled(false);
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenu(evt);
            }
        });
        withdrawButtonsArea.add(Back1);

        Withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Withdraw.setBorder(null);
        Withdraw.setContentAreaFilled(false);
        withdrawButtonsArea.add(Withdraw);

        withdrawPane.setLayer(withdrawButtonsArea, javax.swing.JLayeredPane.PALETTE_LAYER);
        withdrawPane.add(withdrawButtonsArea);
        withdrawButtonsArea.setBounds(0, 290, 402, 46);

        backText1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backText1.setText("Back");
        withdrawPane.setLayer(backText1, javax.swing.JLayeredPane.MODAL_LAYER);
        withdrawPane.add(backText1);
        backText1.setBounds(80, 250, 100, 130);

        depositText1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositText1.setText("Withdraw");
        withdrawPane.setLayer(depositText1, javax.swing.JLayeredPane.MODAL_LAYER);
        withdrawPane.add(depositText1);
        depositText1.setBounds(217, 250, 100, 130);

        Parent.add(withdrawPane, "card2");

        transactionHistoryPane.setPreferredSize(new java.awt.Dimension(402, 437));

        background3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FrameBackground/Frame 1.png"))); // NOI18N
        transactionHistoryPane.add(background3);
        background3.setBounds(0, 0, 402, 437);

        backText2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backText2.setText("Back");
        transactionHistoryPane.setLayer(backText2, javax.swing.JLayeredPane.MODAL_LAYER);
        transactionHistoryPane.add(backText2);
        backText2.setBounds(10, 10, 110, 40);

        Back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Back2.setBorder(null);
        Back2.setContentAreaFilled(false);
        Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenu(evt);
            }
        });
        transactionHistoryPane.setLayer(Back2, javax.swing.JLayeredPane.PALETTE_LAYER);
        transactionHistoryPane.add(Back2);
        Back2.setBounds(10, 10, 111, 36);

        transactionTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        transactionTitle.setForeground(new java.awt.Color(255, 255, 255));
        transactionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionTitle.setText("Transaction History");
        transactionHistoryPane.setLayer(transactionTitle, javax.swing.JLayeredPane.PALETTE_LAYER);
        transactionHistoryPane.add(transactionTitle);
        transactionTitle.setBounds(140, 0, 260, 50);

        javax.swing.GroupLayout cheekyLineLayout = new javax.swing.GroupLayout(cheekyLine);
        cheekyLine.setLayout(cheekyLineLayout);
        cheekyLineLayout.setHorizontalGroup(
            cheekyLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        cheekyLineLayout.setVerticalGroup(
            cheekyLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        transactionHistoryPane.setLayer(cheekyLine, javax.swing.JLayeredPane.PALETTE_LAYER);
        transactionHistoryPane.add(cheekyLine);
        cheekyLine.setBounds(0, 60, 402, 2);

        transactionHistoryPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        transactionHistoryPanel.setOpaque(false);

        javax.swing.GroupLayout transactionHistoryPanelLayout = new javax.swing.GroupLayout(transactionHistoryPanel);
        transactionHistoryPanel.setLayout(transactionHistoryPanelLayout);
        transactionHistoryPanelLayout.setHorizontalGroup(
            transactionHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        transactionHistoryPanelLayout.setVerticalGroup(
            transactionHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        transactionHistoryPane.setLayer(transactionHistoryPanel, javax.swing.JLayeredPane.PALETTE_LAYER);
        transactionHistoryPane.add(transactionHistoryPanel);
        transactionHistoryPanel.setBounds(10, 70, 382, 360);

        Parent.add(transactionHistoryPane, "card2");

        bankTransferPane.setPreferredSize(new java.awt.Dimension(402, 437));

        background4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FrameBackground/Frame 1.png"))); // NOI18N
        bankTransferPane.add(background4);
        background4.setBounds(0, 0, 402, 437);

        profileArea3.setOpaque(false);
        profileArea3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        paneTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paneTitle2.setForeground(new java.awt.Color(255, 255, 255));
        paneTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paneTitle2.setText("Bank Transfer");
        profileArea3.add(paneTitle2);

        bankTransferPane.setLayer(profileArea3, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(profileArea3);
        profileArea3.setBounds(0, 30, 402, 50);

        currentBalanceText3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        currentBalanceText3.setForeground(new java.awt.Color(255, 255, 255));
        currentBalanceText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBalanceText3.setText("₱ 100000");
        bankTransferPane.setLayer(currentBalanceText3, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(currentBalanceText3);
        currentBalanceText3.setBounds(0, 120, 400, 60);

        balanceTitle3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        balanceTitle3.setForeground(new java.awt.Color(255, 255, 255));
        balanceTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceTitle3.setText("Balance");
        bankTransferPane.setLayer(balanceTitle3, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(balanceTitle3);
        balanceTitle3.setBounds(0, 100, 400, 30);

        formattedInputField2.setBorder(null);
        formattedInputField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedInputField2ActionPerformed(evt);
            }
        });
        bankTransferPane.setLayer(formattedInputField2, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(formattedInputField2);
        formattedInputField2.setBounds(90, 207, 220, 16);

        formattedInputFieldBackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattedInputFieldBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/inputFieldBackground.png"))); // NOI18N
        bankTransferPane.setLayer(formattedInputFieldBackground2, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(formattedInputFieldBackground2);
        formattedInputFieldBackground2.setBounds(0, 200, 402, 30);

        enterAmount2.setForeground(new java.awt.Color(255, 255, 255));
        enterAmount2.setText("Enter amount");
        enterAmount2.setToolTipText("");
        enterAmount2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bankTransferPane.setLayer(enterAmount2, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(enterAmount2);
        enterAmount2.setBounds(80, 190, 240, 20);

        depositButtonsArea1.setOpaque(false);
        depositButtonsArea1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        Deposit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Deposit1.setBorder(null);
        Deposit1.setContentAreaFilled(false);
        Deposit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenu(evt);
            }
        });
        depositButtonsArea1.add(Deposit1);

        Back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/buttonSmall.png"))); // NOI18N
        Back3.setBorder(null);
        Back3.setContentAreaFilled(false);
        depositButtonsArea1.add(Back3);

        bankTransferPane.setLayer(depositButtonsArea1, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(depositButtonsArea1);
        depositButtonsArea1.setBounds(0, 360, 402, 46);

        backText3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backText3.setText("Back");
        bankTransferPane.setLayer(backText3, javax.swing.JLayeredPane.MODAL_LAYER);
        bankTransferPane.add(backText3);
        backText3.setBounds(80, 320, 100, 130);

        depositText2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositText2.setText("Transfer");
        bankTransferPane.setLayer(depositText2, javax.swing.JLayeredPane.MODAL_LAYER);
        bankTransferPane.add(depositText2);
        depositText2.setBounds(220, 320, 100, 130);

        formattedInputFieldBackground3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattedInputFieldBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/inputFieldBackground.png"))); // NOI18N
        bankTransferPane.setLayer(formattedInputFieldBackground3, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(formattedInputFieldBackground3);
        formattedInputFieldBackground3.setBounds(0, 240, 402, 30);

        formattedInputField3.setBorder(null);
        formattedInputField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedInputField3ActionPerformed(evt);
            }
        });
        bankTransferPane.setLayer(formattedInputField3, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(formattedInputField3);
        formattedInputField3.setBounds(90, 247, 220, 16);

        enterAmount3.setForeground(new java.awt.Color(255, 255, 255));
        enterAmount3.setText("Sender's Name");
        enterAmount3.setToolTipText("");
        enterAmount3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bankTransferPane.setLayer(enterAmount3, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(enterAmount3);
        enterAmount3.setBounds(80, 230, 240, 20);

        formattedInputFieldBackground4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattedInputFieldBackground4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscellaneous/inputFieldBackground.png"))); // NOI18N
        bankTransferPane.setLayer(formattedInputFieldBackground4, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(formattedInputFieldBackground4);
        formattedInputFieldBackground4.setBounds(0, 280, 402, 30);

        formattedInputField4.setBorder(null);
        formattedInputField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedInputField4ActionPerformed(evt);
            }
        });
        bankTransferPane.setLayer(formattedInputField4, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(formattedInputField4);
        formattedInputField4.setBounds(90, 287, 220, 16);

        enterAmount4.setForeground(new java.awt.Color(255, 255, 255));
        enterAmount4.setText("Receiver's Name");
        enterAmount4.setToolTipText("");
        enterAmount4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bankTransferPane.setLayer(enterAmount4, javax.swing.JLayeredPane.PALETTE_LAYER);
        bankTransferPane.add(enterAmount4);
        enterAmount4.setBounds(80, 270, 240, 20);

        Parent.add(bankTransferPane, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(depositPane);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_depositButtonActionPerformed

    private void bankTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankTransferButtonActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(bankTransferPane);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_bankTransferButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(withdrawPane);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void transactionHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryButtonActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(transactionHistoryPane);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_transactionHistoryButtonActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        dispose();
        EventQueue.invokeLater(() -> new WelcomeWindow().setVisible(true));
    }//GEN-LAST:event_logOutActionPerformed

    private void formattedInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedInputFieldActionPerformed

    private void backToMainMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenu
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(mainMenuLayeredPane);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_backToMainMenu

    private void formattedInputField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedInputField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedInputField1ActionPerformed

    private void formattedInputField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedInputField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedInputField2ActionPerformed

    private void formattedInputField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedInputField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedInputField3ActionPerformed

    private void formattedInputField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedInputField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedInputField4ActionPerformed

    private void notificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(notificationsPane);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_notificationsActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JButton Back2;
    private javax.swing.JButton Back3;
    private javax.swing.JButton Back4;
    private javax.swing.JButton Deposit;
    private javax.swing.JButton Deposit1;
    private javax.swing.JPanel Parent;
    private javax.swing.JButton Withdraw;
    private javax.swing.JLabel backText;
    private javax.swing.JLabel backText1;
    private javax.swing.JLabel backText2;
    private javax.swing.JLabel backText3;
    private javax.swing.JLabel backText4;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel balanceTitle;
    private javax.swing.JLabel balanceTitle1;
    private javax.swing.JLabel balanceTitle2;
    private javax.swing.JLabel balanceTitle3;
    private javax.swing.JButton bankTransferButton;
    private javax.swing.JLayeredPane bankTransferPane;
    private javax.swing.JPanel buttonsArea;
    private javax.swing.JPanel cheekyLine;
    private javax.swing.JPanel cheekyLine1;
    private javax.swing.JLabel currentBalanceText;
    private javax.swing.JLabel currentBalanceText1;
    private javax.swing.JLabel currentBalanceText2;
    private javax.swing.JLabel currentBalanceText3;
    private javax.swing.JButton depositButton;
    private javax.swing.JPanel depositButtonsArea;
    private javax.swing.JPanel depositButtonsArea1;
    private javax.swing.JLayeredPane depositPane;
    private javax.swing.JLabel depositText;
    private javax.swing.JLabel depositText1;
    private javax.swing.JLabel depositText2;
    private javax.swing.JLabel enterAmount;
    private javax.swing.JLabel enterAmount1;
    private javax.swing.JLabel enterAmount2;
    private javax.swing.JLabel enterAmount3;
    private javax.swing.JLabel enterAmount4;
    private javax.swing.JFormattedTextField formattedInputField;
    private javax.swing.JFormattedTextField formattedInputField1;
    private javax.swing.JFormattedTextField formattedInputField2;
    private javax.swing.JFormattedTextField formattedInputField3;
    private javax.swing.JFormattedTextField formattedInputField4;
    private javax.swing.JLabel formattedInputFieldBackground;
    private javax.swing.JLabel formattedInputFieldBackground1;
    private javax.swing.JLabel formattedInputFieldBackground2;
    private javax.swing.JLabel formattedInputFieldBackground3;
    private javax.swing.JLabel formattedInputFieldBackground4;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLayeredPane mainMenuLayeredPane;
    private javax.swing.JButton notificationButton;
    private javax.swing.JLayeredPane notificationsPane;
    private javax.swing.JLabel paneTitle;
    private javax.swing.JLabel paneTitle1;
    private javax.swing.JLabel paneTitle2;
    private javax.swing.JPanel profileArea;
    private javax.swing.JPanel profileArea1;
    private javax.swing.JPanel profileArea2;
    private javax.swing.JPanel profileArea3;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JButton transactionHistoryButton;
    private javax.swing.JLayeredPane transactionHistoryPane;
    private javax.swing.JPanel transactionHistoryPanel;
    private javax.swing.JPanel transactionHistoryPanel1;
    private javax.swing.JLabel transactionTitle;
    private javax.swing.JLabel transactionTitle1;
    private javax.swing.JLabel userName;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JPanel withdrawButtonsArea;
    private javax.swing.JLayeredPane withdrawPane;
    // End of variables declaration//GEN-END:variables
}
