/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

/**
 *
 * @author ORTEGA
 */
public class WelcomeWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WelcomeWindow.class.getName());
    
    
    /**
     * Creates new form WelcomeWindow
     */
    public WelcomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        mainLayeredPane = new javax.swing.JLayeredPane();
        background = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        bankLogo = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        createAccountText = new javax.swing.JLabel();
        signInText = new javax.swing.JLabel();
        signIn = new javax.swing.JLayeredPane();
        background1 = new javax.swing.JLabel();
        exitButton1 = new javax.swing.JButton();
        bankLogo1 = new javax.swing.JLabel();
        passwordFieldBG = new javax.swing.JButton();
        backToMainText = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JPasswordField();
        loginUserNameTextField = new javax.swing.JTextField();
        backToMain = new javax.swing.JButton();
        passwordFieldBG1 = new javax.swing.JButton();
        signInButton3 = new javax.swing.JButton();
        loginText = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        signInTitle = new javax.swing.JLabel();
        createAccount = new javax.swing.JLayeredPane();
        background2 = new javax.swing.JLabel();
        exitButton2 = new javax.swing.JButton();
        bankLogo2 = new javax.swing.JLabel();
        passwordFieldBG2 = new javax.swing.JButton();
        backToMainText1 = new javax.swing.JLabel();
        createPasswordField = new javax.swing.JPasswordField();
        createUserNameTextField = new javax.swing.JTextField();
        backToMain1 = new javax.swing.JButton();
        passwordFieldBG3 = new javax.swing.JButton();
        signInButton4 = new javax.swing.JButton();
        createAccText = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        userNameLabel1 = new javax.swing.JLabel();
        createAccountTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(402, 437));
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        Parent.setMinimumSize(new java.awt.Dimension(402, 437));
        Parent.setPreferredSize(new java.awt.Dimension(402, 437));
        Parent.setLayout(new java.awt.CardLayout());

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame 1.png"))); // NOI18N
        background.setIconTextGap(0);
        mainLayeredPane.add(background);
        background.setBounds(0, 0, 402, 437);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeIcon.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.setContentAreaFilled(false);
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setIconTextGap(0);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        mainLayeredPane.setLayer(exitButton, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(exitButton);
        exitButton.setBounds(370, 10, 30, 30);

        bankLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BankLogo.png"))); // NOI18N
        mainLayeredPane.setLayer(bankLogo, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(bankLogo);
        bankLogo.setBounds(70, 20, 280, 150);

        Text.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Manage your expenses");
        Text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mainLayeredPane.setLayer(Text, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(Text);
        Text.setBounds(60, 210, 220, 30);

        welcomeText.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Welcome");
        mainLayeredPane.setLayer(welcomeText, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(welcomeText);
        welcomeText.setBounds(60, 180, 130, 30);

        Text1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("seamlessly & intuitively");
        Text1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mainLayeredPane.setLayer(Text1, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(Text1);
        Text1.setBounds(60, 250, 220, 30);

        createAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button1.png"))); // NOI18N
        createAccountButton.setBorder(null);
        createAccountButton.setContentAreaFilled(false);
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        mainLayeredPane.setLayer(createAccountButton, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(createAccountButton);
        createAccountButton.setBounds(80, 350, 250, 40);

        signInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button1.png"))); // NOI18N
        signInButton.setBorder(null);
        signInButton.setContentAreaFilled(false);
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInPage(evt);
            }
        });
        mainLayeredPane.setLayer(signInButton, javax.swing.JLayeredPane.PALETTE_LAYER);
        mainLayeredPane.add(signInButton);
        signInButton.setBounds(80, 300, 250, 40);

        createAccountText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createAccountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountText.setText("Create Account");
        mainLayeredPane.setLayer(createAccountText, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.add(createAccountText);
        createAccountText.setBounds(140, 350, 130, 40);

        signInText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInText.setText("Sign In");
        mainLayeredPane.setLayer(signInText, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.add(signInText);
        signInText.setBounds(170, 300, 60, 40);

        Parent.add(mainLayeredPane, "card2");

        signIn.setMinimumSize(new java.awt.Dimension(402, 437));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame 1.png"))); // NOI18N
        background1.setIconTextGap(0);
        signIn.add(background1);
        background1.setBounds(0, 0, 402, 437);

        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeIcon.png"))); // NOI18N
        exitButton1.setBorder(null);
        exitButton1.setContentAreaFilled(false);
        exitButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitButton1.setFocusable(false);
        exitButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton1.setIconTextGap(0);
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        signIn.setLayer(exitButton1, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(exitButton1);
        exitButton1.setBounds(370, 10, 30, 30);

        bankLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BankLogoSmall.png"))); // NOI18N
        signIn.setLayer(bankLogo1, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(bankLogo1);
        bankLogo1.setBounds(70, 40, 280, 70);

        passwordFieldBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inputFieldBackground.png"))); // NOI18N
        passwordFieldBG.setBorder(null);
        passwordFieldBG.setContentAreaFilled(false);
        signIn.setLayer(passwordFieldBG, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(passwordFieldBG);
        passwordFieldBG.setBounds(80, 230, 250, 40);

        backToMainText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backToMainText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backToMainText.setText("Back");
        signIn.setLayer(backToMainText, javax.swing.JLayeredPane.MODAL_LAYER);
        signIn.add(backToMainText);
        backToMainText.setBounds(110, 300, 60, 40);

        loginPasswordField.setToolTipText("Enter your password");
        loginPasswordField.setBorder(null);
        signIn.setLayer(loginPasswordField, javax.swing.JLayeredPane.MODAL_LAYER);
        signIn.add(loginPasswordField);
        loginPasswordField.setBounds(90, 240, 230, 20);

        loginUserNameTextField.setToolTipText("Enter your username");
        loginUserNameTextField.setBorder(null);
        signIn.setLayer(loginUserNameTextField, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(loginUserNameTextField);
        loginUserNameTextField.setBounds(90, 190, 230, 20);

        backToMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonSmall.png"))); // NOI18N
        backToMain.setBorder(null);
        backToMain.setContentAreaFilled(false);
        backToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMain(evt);
            }
        });
        signIn.setLayer(backToMain, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(backToMain);
        backToMain.setBounds(80, 300, 120, 40);

        passwordFieldBG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inputFieldBackground.png"))); // NOI18N
        passwordFieldBG1.setBorder(null);
        passwordFieldBG1.setContentAreaFilled(false);
        signIn.setLayer(passwordFieldBG1, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(passwordFieldBG1);
        passwordFieldBG1.setBounds(80, 180, 250, 40);

        signInButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonSmall.png"))); // NOI18N
        signInButton3.setBorder(null);
        signInButton3.setContentAreaFilled(false);
        signIn.setLayer(signInButton3, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(signInButton3);
        signInButton3.setBounds(210, 300, 120, 40);

        loginText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginText.setText("Log In");
        signIn.setLayer(loginText, javax.swing.JLayeredPane.MODAL_LAYER);
        signIn.add(loginText);
        loginText.setBounds(240, 300, 60, 40);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Pasword");
        passwordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        signIn.setLayer(passwordLabel, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(passwordLabel);
        passwordLabel.setBounds(90, 220, 230, 20);

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("User Name");
        userNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        signIn.setLayer(userNameLabel, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(userNameLabel);
        userNameLabel.setBounds(90, 170, 230, 20);

        signInTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signInTitle.png"))); // NOI18N
        signIn.setLayer(signInTitle, javax.swing.JLayeredPane.PALETTE_LAYER);
        signIn.add(signInTitle);
        signInTitle.setBounds(90, 120, 230, 30);

        Parent.add(signIn, "card3");

        createAccount.setMinimumSize(new java.awt.Dimension(402, 437));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame 1.png"))); // NOI18N
        background2.setIconTextGap(0);
        createAccount.add(background2);
        background2.setBounds(0, 0, 402, 437);

        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeIcon.png"))); // NOI18N
        exitButton2.setBorder(null);
        exitButton2.setContentAreaFilled(false);
        exitButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitButton2.setFocusable(false);
        exitButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton2.setIconTextGap(0);
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        createAccount.setLayer(exitButton2, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(exitButton2);
        exitButton2.setBounds(370, 10, 30, 30);

        bankLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BankLogoSmall.png"))); // NOI18N
        createAccount.setLayer(bankLogo2, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(bankLogo2);
        bankLogo2.setBounds(70, 40, 280, 70);

        passwordFieldBG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inputFieldBackground.png"))); // NOI18N
        passwordFieldBG2.setBorder(null);
        passwordFieldBG2.setContentAreaFilled(false);
        createAccount.setLayer(passwordFieldBG2, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(passwordFieldBG2);
        passwordFieldBG2.setBounds(80, 230, 250, 40);

        backToMainText1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backToMainText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backToMainText1.setText("Back");
        createAccount.setLayer(backToMainText1, javax.swing.JLayeredPane.MODAL_LAYER);
        createAccount.add(backToMainText1);
        backToMainText1.setBounds(110, 300, 60, 40);

        createPasswordField.setToolTipText("Enter your password");
        createPasswordField.setBorder(null);
        createAccount.setLayer(createPasswordField, javax.swing.JLayeredPane.MODAL_LAYER);
        createAccount.add(createPasswordField);
        createPasswordField.setBounds(90, 240, 230, 20);

        createUserNameTextField.setToolTipText("Enter your username");
        createUserNameTextField.setBorder(null);
        createAccount.setLayer(createUserNameTextField, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(createUserNameTextField);
        createUserNameTextField.setBounds(90, 190, 230, 20);

        backToMain1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonSmall.png"))); // NOI18N
        backToMain1.setBorder(null);
        backToMain1.setContentAreaFilled(false);
        backToMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMain(evt);
            }
        });
        createAccount.setLayer(backToMain1, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(backToMain1);
        backToMain1.setBounds(80, 300, 120, 40);

        passwordFieldBG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inputFieldBackground.png"))); // NOI18N
        passwordFieldBG3.setBorder(null);
        passwordFieldBG3.setContentAreaFilled(false);
        createAccount.setLayer(passwordFieldBG3, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(passwordFieldBG3);
        passwordFieldBG3.setBounds(80, 180, 250, 40);

        signInButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonSmall.png"))); // NOI18N
        signInButton4.setBorder(null);
        signInButton4.setContentAreaFilled(false);
        createAccount.setLayer(signInButton4, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(signInButton4);
        signInButton4.setBounds(210, 300, 120, 40);

        createAccText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createAccText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccText.setText("Create");
        createAccount.setLayer(createAccText, javax.swing.JLayeredPane.MODAL_LAYER);
        createAccount.add(createAccText);
        createAccText.setBounds(240, 300, 60, 40);

        passwordLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setText("Pasword");
        passwordLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        createAccount.setLayer(passwordLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(passwordLabel1);
        passwordLabel1.setBounds(90, 220, 230, 20);

        userNameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel1.setText("User Name");
        userNameLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        createAccount.setLayer(userNameLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(userNameLabel1);
        userNameLabel1.setBounds(90, 170, 230, 20);

        createAccountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/createAccountTitle.png"))); // NOI18N
        createAccount.setLayer(createAccountTitle, javax.swing.JLayeredPane.PALETTE_LAYER);
        createAccount.add(createAccountTitle);
        createAccountTitle.setBounds(80, 110, 250, 40);

        Parent.add(createAccount, "card4");

        getContentPane().add(Parent);
        Parent.setBounds(0, 0, 402, 437);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void signInPage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInPage
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(signIn);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_signInPage

    private void backToMain(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMain
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(mainLayeredPane);
        Parent.repaint();
        Parent.revalidate();
        
        loginUserNameTextField.setText("");
        loginPasswordField.setText("");
    }//GEN-LAST:event_backToMain

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(createAccount);
        Parent.repaint();
        Parent.revalidate();
        
        createUserNameTextField.setText("");
        createPasswordField.setText("");
    }//GEN-LAST:event_createAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text1;
    private javax.swing.JButton backToMain;
    private javax.swing.JButton backToMain1;
    private javax.swing.JLabel backToMainText;
    private javax.swing.JLabel backToMainText1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel bankLogo;
    private javax.swing.JLabel bankLogo1;
    private javax.swing.JLabel bankLogo2;
    private javax.swing.JLabel createAccText;
    private javax.swing.JLayeredPane createAccount;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel createAccountText;
    private javax.swing.JLabel createAccountTitle;
    private javax.swing.JPasswordField createPasswordField;
    private javax.swing.JTextField createUserNameTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginText;
    private javax.swing.JTextField loginUserNameTextField;
    private javax.swing.JLayeredPane mainLayeredPane;
    private javax.swing.JButton passwordFieldBG;
    private javax.swing.JButton passwordFieldBG1;
    private javax.swing.JButton passwordFieldBG2;
    private javax.swing.JButton passwordFieldBG3;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLayeredPane signIn;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signInButton3;
    private javax.swing.JButton signInButton4;
    private javax.swing.JLabel signInText;
    private javax.swing.JLabel signInTitle;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLabel1;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
